### ISSUE TITLE
[BUG] Private repository reference cannot be processed by `yarn`

### ISSUE THREAD

**Issue by llaszkie** [devonfw-react-training/foundation-2021#16]
https://github.com/devonfw-react-training/foundation-2021/blob/a102c411ed0119c87284056d402f62639a94725c/yarn.lock#L30

401 after `yarn install`

**Comment by agatatocz** [comment]
Generated new yarn.lock for all the branches. Should be fine now

**Comment by llaszkie** [comment]
I've checked on `05-routing`. All fine. Thanks! :)
